module.exports = {
	'FACEBOOK_APP_ID' : process.env.FACEBOOK_APP_ID,
	'FACEBOOK_APP_SECRET' : process.env.FACEBOOK_APP_SECRET,
	'FACEBOOK_CALLBACK_URL': process.env.FACEBOOK_CALLBACK_URL,
	'NYTIMES_API_KEY' : process.env.NYTIMES_API_KEY,
	'MONGO_URI' : process.env.MONGO_URI}